sources:
    - Commissioner.glyphs
buildStatic: false
familyName: Commissioner
axisOrder:
    - FLAR
    - VOLM
    - wght
    - slnt
stat:
  - name: Flair
    tag: FLAR
    values:
    - name: Default
      value: 0
      flags: 2
  - name: Volume
    tag: VOLM
    values:
    - name: Default
      value: 0
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Slant
    tag: slnt
    values:
    - name: Default
      value: 0
      linkedValue: -12
      flags: 2
    - name: Italic
      value: -12
statFormat4:
    - name: Flair
      location:
        FLAR: 100
        VOLM: 0
    - name: Loud
      location:
        FLAR: 100
        VOLM: 100

